var a;
document.write("Value after variable declaration is " + typeof a + '</br>');
a = 5;
document.write("Initial value:  " + a + '</br>' );
a++;
document.write("Value after increment is:  " + a + '</br>' );
a = a + 7;
document.write("Value after addition is:  " + a + '</br>' );
a--;
document.write("Value after decrement is:  " + a + '</br>' );
a %= 3;
document.write("Remainder after dividing by 3 is:  " + a + '</br>' );